BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE processors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (name = lower(name))
);
CREATE TABLE processor_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_id INTEGER NOT NULL REFERENCES processors(id) ON DELETE RESTRICT,
    account_name TEXT NOT NULL,
    credential_ref TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (processor_id, account_name)
);
CREATE TABLE sync_state (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_account_id INTEGER NOT NULL UNIQUE REFERENCES processor_accounts(id) ON DELETE CASCADE,
    last_cursor TEXT,
    cursor_version BIGINT NOT NULL DEFAULT 0 CHECK (cursor_version >= 0),
    last_synced_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE raw_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_account_id INTEGER NOT NULL REFERENCES processor_accounts(id) ON DELETE RESTRICT,
    processor TEXT NOT NULL,
    event_type TEXT NOT NULL,
    external_id TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    payload_sha256 TEXT NOT NULL CHECK (
        payload_sha256 = encode(digest(payload_json::text, 'sha256'), 'hex')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (processor_account_id, event_type, external_id)
);
CREATE TABLE ledger_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    processor TEXT NOT NULL,
    processor_account_id INTEGER NOT NULL REFERENCES processor_accounts(id) ON DELETE RESTRICT,
    external_id TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('charge', 'payment', 'refund', 'reversal', 'fee')),
    gross_amount NUMERIC(18,2) NOT NULL,
    fee_amount NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (fee_amount >= 0),
    net_amount NUMERIC(18,2) NOT NULL,
    currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    occurred_at TIMESTAMPTZ NOT NULL,
    customer_ref TEXT,
    description TEXT,
    status TEXT NOT NULL,
    UNIQUE (processor_account_id, external_id)
);
CREATE INDEX idx_ledger_occurred_at ON ledger_transactions (occurred_at);
CREATE TABLE ledger_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID NOT NULL REFERENCES ledger_transactions(id) ON DELETE CASCADE,
    related_transaction_id UUID NOT NULL REFERENCES ledger_transactions(id) ON DELETE CASCADE,
    relation_type TEXT NOT NULL CHECK (relation_type IN ('refund_of', 'reversal_of', 'split_of')),
    CHECK (transaction_id <> related_transaction_id),
    UNIQUE (transaction_id, related_transaction_id, relation_type)
);
CREATE TABLE payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor TEXT NOT NULL,
    processor_account_id INTEGER NOT NULL REFERENCES processor_accounts(id) ON DELETE RESTRICT,
    external_id TEXT NOT NULL,
    payout_amount NUMERIC(18,2) NOT NULL,
    currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    payout_date DATE NOT NULL,
    status TEXT NOT NULL,
    UNIQUE (processor_account_id, external_id)
);
CREATE TABLE recon_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_window_start TIMESTAMPTZ NOT NULL,
    time_window_end TIMESTAMPTZ NOT NULL,
    processors_included TEXT[] NOT NULL,
    input_fingerprint TEXT NOT NULL CHECK (input_fingerprint ~ '^[0-9a-f]{64}$'),
    stats JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (time_window_end >= time_window_start),
    UNIQUE (input_fingerprint)
);
CREATE TABLE recon_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES recon_runs(id) ON DELETE CASCADE,
    match_key TEXT NOT NULL,
    left_entity_type TEXT NOT NULL,
    left_entity_id TEXT NOT NULL,
    right_entity_type TEXT NOT NULL,
    right_entity_id TEXT NOT NULL,
    confidence NUMERIC(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    reason TEXT NOT NULL,
    UNIQUE (run_id, match_key)
);
CREATE TABLE recon_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES recon_runs(id) ON DELETE CASCADE,
    exception_type TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    entity_ref TEXT NOT NULL,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    resolved_at TIMESTAMPTZ,
    UNIQUE (run_id, exception_type, entity_ref)
);
CREATE TABLE qb_sync_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT REFERENCES recon_runs(id) ON DELETE SET NULL,
    idempotency_key TEXT NOT NULL UNIQUE,
    payload_sha256 TEXT NOT NULL CHECK (
        payload_sha256 = encode(digest(qb_payload_json::text, 'sha256'), 'hex')
    ),
    status TEXT NOT NULL CHECK (status IN ('pending', 'posting', 'posted', 'failed')),
    qb_payload_json JSONB NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE qb_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_job_id BIGINT NOT NULL UNIQUE REFERENCES qb_sync_jobs(id) ON DELETE RESTRICT,
    clearing_account TEXT NOT NULL,
    journal_entry_id TEXT NOT NULL UNIQUE,
    debit_total NUMERIC(18,2) NOT NULL CHECK (debit_total >= 0),
    credit_total NUMERIC(18,2) NOT NULL CHECK (credit_total >= 0),
    currency TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    posted_at TIMESTAMPTZ NOT NULL,
    CHECK (debit_total = credit_total)
);
COMMIT;
